"""add topic to quiz

Revision ID: fa66ab6b4b48
Revises: d6176dba237e
Create Date: 2026-04-03 17:01:54.654850

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel             # NEW
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa66ab6b4b48'
down_revision: Union[str, None] = 'd6176dba237e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'topic')
    # ### end Alembic commands ###
