"""add new fields

Revision ID: 8839071610bb
Revises: fa66ab6b4b48
Create Date: 2026-04-03 21:44:36.522725

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel             # NEW
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8839071610bb'
down_revision: Union[str, None] = 'fa66ab6b4b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
